[build-system]
requires = ["setuptools>=82.0.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unified-ui"
version = "0.1.2"
description = "A unified UI framework built on Flet"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
dependencies = ["flet>=0.25.0"]

[tool.setuptools]
package-dir = {"unified_ui" = "unified_ui/scripts", "unified_ui.themes" = "unified_ui/themes"}
packages = ["unified_ui", "unified_ui.themes"]

[tool.setuptools.package-data]
"unified_ui.themes" = ["*.json"]